### Generated by rprotoc. DO NOT EDIT!
### <proto file: addressbook.proto>
# package examples;
# 
# /**
#  * Defines a Person in the addressbook
#  */
# message Person {
#   /* The full name of the person */
#   required string name = 1;
#   /* The person Id in the database */
#   required int32 id = 2;
#   /* The person email */
#   optional string email = 3;
# 
#   /* Different types of phones */
#   enum PhoneType {
#     MOBILE = 0;
#     HOME = 1;
#     WORK = 2;
#   }
# 
#   /* A phone number record */
#   message PhoneNumber {
#     required string number = 1;
#     optional PhoneType type = 2 [default = HOME];
#   }
# 
#   /* The different phone numbers associated to a person */
#   repeated PhoneNumber phone = 4;
# }
# 
# 
# /* A collection of persons contact details */
# message AddressBook {
#   repeated Person person = 1;
# 
#   extensions 1000 to max;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Examples
  class Person < ::Protobuf::Message
    defined_in __FILE__
    required :string, :name, 1
    required :int32, :id, 2
    optional :string, :email, 3
    class PhoneType < ::Protobuf::Enum
      defined_in __FILE__
      MOBILE = value(:MOBILE, 0)
      HOME = value(:HOME, 1)
      WORK = value(:WORK, 2)
    end
    class PhoneNumber < ::Protobuf::Message
      defined_in __FILE__
      required :string, :number, 1
      optional :PhoneType, :type, 2, :default => :HOME
    end
    repeated :PhoneNumber, :phone, 4
  end
  class AddressBook < ::Protobuf::Message
    defined_in __FILE__
    repeated :Person, :person, 1
    extensions 1000..::Protobuf::Extend::MAX
  end
end