### Generated by rprotoc. DO NOT EDIT!
### <proto file: repeated.proto>
# package examples;
# 
# message Repeated {
# 
#   message Nested {
#     optional int32 id = 1;
#   }
# 
#   repeated string string = 1;
#   repeated int32 int = 2;
#   repeated Nested nested = 3;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Examples
  class Repeated < ::Protobuf::Message
    defined_in __FILE__
    class Nested < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :id, 1
    end
    repeated :string, :string, 1
    repeated :int32, :int, 2
    repeated :Nested, :nested, 3
  end
end